version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./maturita/:/var/www/html/maturita/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./maturita/:/var/www/html/maturita/
  mysql:
    image: mysql:5.6.40
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    command: --init-file /data/application/MaturitaDatabase.sql
    volumes:
      - ./db/MaturitaDatabase.sql:/data/application/MaturitaDatabase.sql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=MaturitaDatabase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test123
networks:
  frontend:
  backend: